# Site settings
title: TY Blog
SEOTitle: 雨枫的博客 | TY Blog
header-img: img/post-bg-desk.jpg
email: tssadltw@gmail.com
description: "We need success."
keyword: "TY, TY Blog, 雨枫的博客, Taoyu, 陶宇, Java, Tensorflow, Web"
url: "https://rainmaple.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/rainmaple/rainmaple.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "I Come,I See,I Conque!"
sidebar-avatar: /img/about-personal.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     Rainmaple20186
csdn_username:     rainmaple20186
github_username:    rainmaple
jianshu_username:   f0dadea7f4e1





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4b06fe87f3e564117604  #生成的clientID
  clientSecret: 6ee3e4d6183edfa0b6b527426a2eea3e3be6aae4  #同上
  repo: rainmaple.github.io    #仓库名称
  owner: rainmaple    #github用户名
  admin: rainmaple
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "个人网站",
        href: "https://www.supersuperhandsome.cn"
    },{
        title: "简书·TY",

        href: "http://www.jianshu.com/u/f0dadea7f4e1"
    },{
        title: "tensorflow",
        href: "http://www.tensorfly.cn"
    },{
        title: "Java Developer",
        href: "https://my.csdn.net/rainmaple20186"
    },
    {
      title: "My Resume",
        href: "https://www.supersuperhandsome.cn/ty_persWebsite/resume/resume.html"

    }
]
